QUESTION_TEMPLATE = {
    "disambiguity_question": {
        "singular": {
            "question": [
                "Can {objects} satisfy your requirement?",
                "Is {objects} okay?",
                "Can {objects} meet your needs?",
                "Would a {objects} work for you?",
                "Is a {objects} what you are looking for?",
                "Does {objects} fit your requirements?",
                "Will {objects} do the job?",
                "Would {objects} be suitable for you?",
                "Is {objects} what you had in mind?",
                "Does {objects} match your expectations?",
                "Will {objects} satisfy your preferences?",
                "Would you be happy with {objects}?",
            ],
            "answer": {
                "yes": [
                    "{objects} is exactly what I need.",
                    "{objects} would work perfectly.",
                    "{objects} meets my requirements.",
                    "{objects} is suitable for my needs.",
                    "{objects} matches my expectations.",
                    "That's great, {objects} is just what I am looking for.",
                    "Perfect, {objects} will do the job nicely.",
                    "I'm happy with {objects}.",
                    "{objects} satisfies my preferences.",
                    "{objects} is what I had in mind.",
                ],
                "no": [
                    "No, maybe a {objects} will meet my requirements.",
                    "Unfortunately, a {objects} could be more suitable for me.",
                    "No, but a {objects} will work for what I need.",
                    "Sorry, but a {objects} is what I am looking for.",
                    "No, {objects} matches my expectations more.",
                    "No, sorry, I think a {objects} can be better.",
                    "No, your offer isn't quite what I had in mind. I prefer a {objects}",
                    "I will be more happy with a {objects}.",
                    "No, that doesn't satisfy my preferences. A {objects} may be okay",
                    "Sorry, but it is not what I need. You can find me a {object} instead",
                ],
            },
        },
        "plural": {
            "question": [
                "Can {objects} satisfy your requirements?",
                "Are {objects} okay?",
                "Can {objects} meet your needs?",
                "Would {objects} work for you?",
                "Are {objects} what you are looking for?",
                "Do {objects} fit your requirements?",
                "Will {objects} do the job?",
                "Would {objects} be suitable for you?",
                "Are {objects} what you had in mind?",
                "Do {objects} match your expectations?",
                "Will {objects} satisfy your preferences?",
                "Would you be happy with {objects}?",
            ],
            "answer": {
                "yes": [
                    "{objects} are exactly what I need.",
                    "{objects} would work perfectly.",
                    "{objects} meet my requirements.",
                    "{objects} are suitable for my needs.",
                    "{objects} match my expectations.",
                    "That's great, {objects} are just what I am looking for.",
                    "Perfect, {objects} will do the job nicely.",
                    "I'm happy with {objects}.",
                    "{objects} satisfy my preferences.",
                    "{objects} are what I had in mind.",
                ],
                "no": [
                    "No, maybe a {objects} will meet my requirements.",
                    "Unfortunately, a {objects} could be more suitable for me.",
                    "No, but a {objects} will work for what I need.",
                    "Sorry, but a {objects} is what I am looking for.",
                    "No, {objects} matches my expectations more.",
                    "No, sorry, I think a {objects} can be better.",
                    "No, your offers aren't quite what I had in mind. I prefer a {objects}",
                    "I will be more happy with a {objects}.",
                    "No, they don't satisfy my preferences. A {objects} may be okay",
                    "Sorry, but they are not what I need. You can find me a {object} instead",
                ],
            },
        },
    },
    "position_question": {
        "question": {
            "first": [
                "Please give me a place that can find the target.",
                "Where can I find the target?",
                "Can you tell me the location of the target?",
                "What is the best place to locate the target?",
                "Where should I go to find the target?",
                "Is there a specific area where the target can be found?",
                "Could you provide me with the target's whereabouts?",
                "What location should I check for the target?",
                "Can you guide me to the target's location?",
                "Where exactly is the target situated?",
                "Do you know where I can find the target?",
            ],
            "after": [
                "Can you provide additional details about the location?",
                "What more can you tell me about the place I should visit?",
                "Could you elaborate on the specifics of the position?",
                "I would appreciate more information regarding the location.",
                "Can you share further insights about where to go?",
                "What additional details do you have about the target's position?",
                "Please tell me more about the area I should check.",
                "Could you give me a clearer description of the place?",
                "What else can you inform me about the location?",
                "Can you specify more about the position I need to find?",
            ],
        },
        "answer": {
            "first": [
                "You can find the target in the {position}.",
                "Maybe the {position}.",
                "The target should be around the {position}.",
                "You might wanna check out the {position}.",
                "I think the {position} is where you'll find it.",
                "How about looking in the {position}?",
                "The {position} could be a good spot to find it.",
                "You could try the {position} for the target.",
            ],
            "after": [
                "New information about the {position} is available:\n{new_info}",
                "Here is the latest update regarding the {position}:\n{new_info}",
                "Updated details for the {position}:\n{new_info}",
                "We have new information on the {position}:\n{new_info}",
                "There is new information concerning the {position}:\n{new_info}",
                "Fresh information has been reported for the {position}:\n{new_info}",
                "I just got an update on the {position}:\n{new_info}",
                "Here's something new about the {position}:\n{new_info}",
                "Just learned something new about the {position}:\n{new_info}",
                "Hey, check this out-new info on the {position}:\n{new_info}",
                "Here is a fresh update for the {position}:\n{new_info}",
                "The {position} now has some updated details:\n{new_info}",
                "Got more clarity on the {position}:\n{new_info}",
                "Update just in for the {position}:\n{new_info}",
            ],
        },
    },
    "local_question": {
        "question": [
            "Where should I go now?",
            "Where to?",
            "What's next?",
            "Where do I head from here?",
            "What's the next step?",
            "Where do I go from here?",
            "Which way should I go?",
            "Where am I expected to go next?",
            "Which route should I take?",
            "What should I aim for next?",
            "Where do I need to go next?",
            "Where am I expected to go next?",
        ],
        "answer": [
            "Just turn {turn}.",
            "Look to your {turn}.",
            "You should turn to your {turn}.",
        ],
    },
    "object_info_question": {
        "question": [
            "Please tell me more about the target object.",
            "Can you describe the target object in more detail?",
            "Could you provide more information about the target object?",
            "What details can you share about the target object?",
            "Can you give me a more detailed description of the target object?",
            "Can you be more specific about the target object?",
            "Can you describe the target object as thoroughly as possible?",
            "What should I be focusing on when looking for the target object?",
            "What makes the target object unique or distinctive?",
            "Are there any special features of the target object I should know about?",
            "What details should I pay attention to when identifying the target object?",
            "Is there anything else you can tell me to help me identify the target object?",
            "Could you describe the target object as completely as possible?",
            "Can you provide any additional information about the target object?",
            "What other details should I be aware of about the target object?",
            "Is there anything else about the target object I should know?",
            "What other characteristics can you mention about the target object?",
            "What specific attributes should I be looking for in the target object?",
        ],
        "answer": [
            "The target object is a {unique_description}",
            "The object you are looking for is a {unique_description}",
            "The target item is described as a {unique_description}",
            "The object in question is a {unique_description}",
            "The desired object is a {unique_description}",
            "The target object is specifically a {unique_description}",
            "The object you should find is a {unique_description}",
            "The intended object is a {unique_description}",
            "The object to identify is a {unique_description}",
            "The required object is a {unique_description}",
            "The target object is uniquely a {unique_description}",
            "The object you need to find is a {unique_description}",
            "The particular object you're looking for is a {unique_description}",
            "The object to locate is a {unique_description}",
            "The target object can be identified as a {unique_description}",
        ],
    },
    "position_confirm_question": {
        "question": [
            "Am I in the correct position?",
            "Am I in the right place?",
            "Is here?",
            "Am I where supposed to be?",
            "Have I reached the right spot?",
            "Is this the intended position?",
            "Am I in the proper location?",
            "Am I at the right destination?",
            "Am I in the right area?",
            "Have I arrived at the correct place?",
            "Is this the expected position?",
            "Am I aligned correctly?",
            "Am I positioned correctly?",
            "Is this where I should be?",
            "Am I at the correct checkpoint?",
            "Is this the appropriate position?",
            "Am I located where I should be?",
            "Am I situated correctly?",
            "Is this the right spot?",
            "Am I standing in the right place?",
            "Is this the correct point?",
            "Am I at the correct marker?",
            "Am I correctly positioned?",
            "Am I currently in the right place?",
            "Am I at the intended destination?",
            "Am I where I need to be?",
            "Is this the planned location?",
            "Am I correctly placed?",
            "Am I accurately located?",
            "Is my position correct?",
            "Is this the proper place for me?",
        ],
        "answer": {
            "yes": [
                "Yes, you are in the correct position.",
                "That's right, you are at the intended location.",
                "Yes, you have reached the right spot.",
                "Correct, you are in the proper place.",
                "Yes, you are exactly where you need to be.",
                "Yes, you are aligned correctly.",
                "Yes, you are positioned accurately.",
                "Everything looks good, you are at the correct location.",
                "You are in the right area.",
                "Yes, you are currently at the correct position.",
                "That's perfect, you are in the right spot.",
                "Yes, your position is accurate.",
                "You have reached the proper location.",
                "Yes, you are at the specified position.",
                "Everything is aligned properly, you're in the correct spot.",
                "Yes, you are where you should be.",
                "Yes, this is the right place.",
            ],
            "no": [
                "This is not the intended location.",
                "You are not in the proper place.",
                "No, you are not where you need to be.",
                "No, you are not aligned correctly.",
                "No, you are positioned incorrectly.",
                "You are not at the correct location.",
                "No, you are situated incorrectly.",
                "You are in the wrong area.",
                "No, you are not currently at the correct position.",
                "That's not the right spot.",
                "No, you are not at the intended destination.",
                "Your position is inaccurate.",
                "You haven't reached the proper location.",
                "No, you are not at the specified position.",
                "The alignment is off, you are in the wrong spot.",
                "This is not the right place.",
            ],
        },
    },
    "object_confirm_question": {
        "question": [
            "Is this the target?",
            "Is this what you are looking for?",
            "Is this the intended object?",
            "Is this the correct item?",
            "Is this the object you wanted me to find?",
            "Have I found what you are searching for?",
            "Does this match the description you provided?",
            "Is this what you had in mind?",
            "Is this the goal you wanted me to reach?",
            "Is this the object you were expecting me to find?",
            "Does this fulfill the criteria you mentioned?",
            "Is this the object you are aiming for?",
            "Is this the right choice?",
            "Is this the object you described?",
            "Is this the correct option?",
            "Did I locate the correct object?",
            "Does this item meet your requirements?",
            "Have I reached the intended target?",
            "Does this match your expectations?",
            "Is this the object you hope to find?",
            "Is this what you needed?",
            "Is this the object you referred to?",
            "Is this what you meant?",
            "Is this the thing you described?",
        ],
        "answer": {
            "yes": [
                "Yes, this is the target.",
                "That's correct, you find it.",
                "Yes, that's exactly what I am looking for.",
                "Perfect, this is the right one.",
                "You nailed it! This is what I wanted.",
                "Yes, this matches the description perfectly.",
                "That's exactly what I referred to.",
                "Yes, you've got it right.",
                "Yes, this is exactly what I needed.",
                "Absolutely, this is the correct item.",
                "Yes, this meets the requirements.",
                "That's the one I described.",
                "Yes, you've located the correct object.",
                "Correct, that's the item I wanted.",
                "Yes, that's the intended object.",
                "Yes, that's the one!",
                "You find it!",
                "Exactly, that's what I meant.",
                "That's it, well done!",
                "Yes, this is the object I had in mind.",
                "Yes, that's perfect. Good job!",
                "Yes, that's spot on!",
                "Absolutely, you've found the right thing.",
            ],
            "no": [
                "No, this is not the target.",
                "Sorry, that's not the correct one.",
                "No, that's not what I am looking for.",
                "This doesn't seem right.",
                "No, you haven't found it yet.",
                "Close, but that's not quite it.",
                "No, this doesn't match the description I provided.",
                "Not exactly, that's not what I meant.",
                "Sorry, but that's not the right one.",
                "No, try again.",
                "That's not the intended object. Please try once more.",
                "No, I think you missed it.",
                "No, this doesn't fit the criteria.",
                "No, that's not the item I was describing.",
                "Nope, that's not it.",
                "Not quite, try again.",
                "No, this isn't what I had in mind.",
                "That's not the right thing.",
                "Sorry, that's not the object I was referring to.",
                "No, this doesn't fulfill the requirements.",
                "Sorry, this isn't the desired object.",
                "Unfortunately, this isn't what I expect.",
                "No, that's not what I hope to find.",
                "No, this isn't the correct choice.",
            ],
        },
    },
}

INFORMATION_TEMPLATE = [
    "What is the {ma} of the {instance_category}?",
    "Tell me the {ma} of the {instance_category}?",
]

STAIRS_TEMPLATE = [
    {
        "question": [
            "Where should I go now?",
            "Where to?",
            "What's next?",
            "Where do I head from here?",
            "What's the next step?",
            "Where do I go from here?",
            "Which way should I go?",
            "Where am I expected to go next?",
            "Which route should I take?",
            "What should I aim for next?",
            "Where do I need to go next?",
            "Where am I expected to go next?",
        ],
        "answer": [
            "Go {up_or_down}stairs.",
            "Just go {up_or_down}stairs.",
            "Search in {up_or_down}stairs.",
        ],
    },
    {
        "question": [
            "Should I change the floor?",
            "Maybe I should change the floor?",
            "Is the target in different floor?",
            "Is the goal object in different floor?",
        ],
        "answer": [
            "Yes, please go {up_or_down}stairs to have a look.",
            "Yes, target is in {up_or_down}stairs.",
            "Yes, the target object is in {up_or_down}stairs.",
        ],
    },
]
